"""Add desc to horoscope model.

Revision ID: c0b1c790e428
Revises: c3906e5bfa01
Create Date: 2022-04-05 18:24:04.246984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b1c790e428'
down_revision = 'c3906e5bfa01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscope', sa.Column('desc', sa.String(), nullable=True))
    op.drop_constraint('horoscope_is_day_key', 'horoscope', type_='unique')
    op.create_unique_constraint(None, 'horoscope', ['name'])
    op.drop_column('horoscope', 'is_day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horoscope', sa.Column('is_day', sa.VARCHAR(), server_default=sa.text("'FALSE'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'horoscope', type_='unique')
    op.create_unique_constraint('horoscope_is_day_key', 'horoscope', ['is_day'])
    op.drop_column('horoscope', 'desc')
    # ### end Alembic commands ###
