version: '3'

services:
  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: horoscope
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  horoscope:
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        CONFIG_NAME: DevelopmentConfig
        SQLALCHEMY_DATABASE_URI: postgresql+pg8000://app:password@pg/horoscope
      ports:
        - "5050:5000"
      volumes:
        - ./:/app
      depends_on:
        - pg

  horoscope-prod:
      build:
        context: .
        dockerfile: docker-build/Dockerfile
      environment:
        CONFIG_NAME: ProductionConfig
        SQLALCHEMY_DATABASE_URI: postgresql+pg8000://app:password@pg/horoscope
      ports:
        - "5080:80"
      depends_on:
        - pg

volumes:
  pg-data:
