# Generated by Django 4.0.3 on 2022-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_customer_email_customer_phone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('A', 'Active'), ('F', 'Finished')], default='C', max_length=1),
        ),
    ]
