# Generated by Django 4.0.3 on 2022-03-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_manufacturer_product_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('BK', 'Black'), ('WT', 'White'), ('BR', 'Brown'), ('RD', 'Red')], default='BK', max_length=2)),
                ('size', models.IntegerField(choices=[(38, '38'), (40, '40'), (42, '42'), (44, '44'), (46, '46')], default=38)),
                ('gender', models.CharField(choices=[('C', 'Child'), ('M', 'M'), ('F', 'F')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='property',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productproperty'),
        ),
    ]
